### ISSUE TITLE
Error plugin crash because of biome change

### ISSUE THREAD

**Issue by Hordoss** [nmahdi/FishingRewards#3]
Hi,
I would like to make a reward on a specific biome but when i did it, the plugin crashed and sent an error
Maybe i used the wrong biome ID ?
Here is the error : 

`[21:19:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fishingrewards' in plugin FishingRewards v3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.20.2.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-223]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2207) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2167) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-223]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.warm_ocean
        at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.block.Biome.valueOf(Biome.java:11) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.fishingrewards.rewards.RewardConfiguration.getBiomes(RewardConfiguration.java:170) ~[Fishing Rewards 3.0.jar:?]
        at com.fishingrewards.managers.RewardManager.loadRewards(RewardManager.java:83) ~[Fishing Rewards 3.0.jar:?]
        at com.fishingrewards.managers.RewardManager.reload(RewardManager.java:97) ~[Fishing Rewards 3.0.jar:?]
        at com.fishingrewards.commands.FishingRewardsCommand.onCommand(FishingRewardsCommand.java:54) ~[Fishing Rewards 3.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
`

Here is my config: 

Cod:
    material: 'cod'
    type: 'item'
    chance: 50
Salmon:
    material: 'salmon'
    type: 'item'
    chance: 25
Clownfish:
    material: 'tropical_fish'
    biomes:
     - 'warm_ocean'
     - 'lukewarm_ocean'
     - 'deep_lukewarm_ocean'
     - 'ocean'
     - 'deep_ocean'
    type: 'item'
    chance: 200
Pufferfish:
    material: 'pufferfish'
    type: 'item'
    chance: 13
NautilusShell:
    material: 'nautilus_shell'
    type: 'item'
    chance: 20
    treasure: true
LilyPad:
    material: 'lily_pad'
    type: 'item'
    chance: 10
    junk: true

thank you for your help

**Comment by nmahdi** [comment]
Hello, I apparently forgot to ignore caps for biomes. I'm not sure when I'll be able to push out an update, so for now try having all of the letters capitalized so the plugin is able to read them. Let me know if that doesn't work. Sorry for the inconvenience.

**Comment by Hordoss** [comment]
Hello
No problem, thank you very much for your responsiveness! :)
Have a nice day

**Comment by nmahdi** [comment]
No problem, glad the issue was resolved.

**Comment by nmahdi** [comment]
No problem, glad the issue was resolved.
