### ISSUE TITLE
我这里好像有一个报错

### ISSUE THREAD

**Issue by nenglizuida** [nmahdi/FishingRewards#5]
[14:23:31 ERROR]: Could not pass event PlayerFishEvent to FishingRewards v3.0
java.lang.IllegalArgumentException: Material cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:140) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at [自定义钓鱼]Fishing.Rewards.3.0.jar/com.fishingrewards.rewards.item.ItemStackBuilder.buildFromContainer(ItemStackBuilder.java:34) ~[[自定义钓鱼]Fishing.Rewards.3.0.jar:?]
        at [自定义钓鱼]Fishing.Rewards.3.0.jar/com.fishingrewards.managers.FishingManager.attachToRod(FishingManager.java:203) ~[[自定义钓鱼]Fishing.Rewards.3.0.jar:?]
        at [自定义钓鱼]Fishing.Rewards.3.0.jar/com.fishingrewards.managers.FishingManager.onFish(FishingManager.java:176) ~[[自定义钓鱼]Fishing.Rewards.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor77.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2309-be61a07]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:543) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:33) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:605) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:489) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2111) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

但是我看我写的 Material 都是正常的 且都正确加载了

**Comment by nmahdi** [comment]
Hello. Can you post the entire section for reward? Keep in mind the plugin doesn't have 1.21 support yet, so if it's a new item it will most likely not work.

**Comment by nenglizuida** [comment]
https://github.com/vlssu/fishing-award/blob/void/rewards.yml  You can see my edits here: Here's a list of my updates to server syncs

**Comment by nenglizuida** [comment]
weather: 'rain'
This is also reported in the purpur server in 1.21.1 
![58F7182BC4FE562CFDAA1A9865CE31AA](https://github.com/user-attachments/assets/b5dd0f86-ed9b-46c3-81b0-ee8487987ccb)

**Comment by nenglizuida** [comment]
Hopefully you can support it to 1.21.1 so that I can add more content in the new version.

**Comment by nmahdi** [comment]
In your rewards.yml, 'waterlily' isn't a part of spigot 1.20, removing that should stop giving you that null pointer. For the weather condition I forgot to ignore capitalizations, so use 'RAIN' instead of 'rain' and that should fix the second issue.
I'm currently working on an update that will include 1.21 support, but I've been busy as it's exam week at my college. The update's content is done, all I have left is to bug fix and optimize a few things. Hopefully I can release it within the next couple weeks.
Hopefully this solved all of your issues.

**Comment by nenglizuida** [comment]
Thank you
 weather: 'CLEAR' is working
